// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Tr4pTu9cnlUqSakN92DxMNa2jtgcz38',
    appId: '1:494438016572:web:920d2a5f782de7360e4539',
    messagingSenderId: '494438016572',
    projectId: 'plypicker-project-assi',
    authDomain: 'plypicker-project-assi.firebaseapp.com',
    storageBucket: 'plypicker-project-assi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8AKaGbylrGo24bKjayP87l4xGpBrwKU',
    appId: '1:494438016572:android:b908766cdec1542a0e4539',
    messagingSenderId: '494438016572',
    projectId: 'plypicker-project-assi',
    storageBucket: 'plypicker-project-assi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8hyndjihG6XQnEZLR0khqqh7sY3wKl0',
    appId: '1:494438016572:ios:5eb52451dd730eb30e4539',
    messagingSenderId: '494438016572',
    projectId: 'plypicker-project-assi',
    storageBucket: 'plypicker-project-assi.appspot.com',
    iosBundleId: 'com.example.plypickerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8hyndjihG6XQnEZLR0khqqh7sY3wKl0',
    appId: '1:494438016572:ios:0886173df75dd8820e4539',
    messagingSenderId: '494438016572',
    projectId: 'plypicker-project-assi',
    storageBucket: 'plypicker-project-assi.appspot.com',
    iosBundleId: 'com.example.plypickerFlutter.RunnerTests',
  );
}
